### ISSUE TITLE
Orientation of Baxter Gripper

### ISSUE THREAD

**Issue by ktiwari9** [haxelion/baxter_pickandlearn#1]
Hey there,
I am new to using ROS and Baxter. I am learning ROS Hydro and using Baxter for my project where the aim is to detect and grasp a Printed Circuit Board. Now I have a vision module that detects the Printed Circuit Board in the environment but I do not know how to orient the gripper according to the orientation of the PCB. Is there a piece of your code I could replicate to realise this ?
Please advise.

**Comment by haxelion** [comment]
Hey ;-)

Unfortunately I had no time to implement that in my project so I can't show you a specific code. But it's not very difficult to do.

Basically you have to compute the image moment (http://en.wikipedia.org/wiki/Image_moment) (openCV has a function).Then you can use the image moment to get the orientation. You have two useful moments: m01 and m10 which are basically the repartition of pixels in the x axis and y axis. The orientation would be a vector defined by these two moments.

Hope that helps, don't hesitate to ask another question ;-)
