### ISSUE TITLE
Pick and learn

### ISSUE THREAD

**Issue by ghost** [haxelion/baxter_pickandlearn#2]
Hi, 

I downloaded your program and tried running the same on baxter. Also, I have seen the video on youtube. For using the gripper to pick the object, I saw you pressing the wheel. But, when I am training the baxter, I am unable to make baxter pick the object. I tried pressing the wheel but baxter is not operating grippers. Please let me know how to solve this.

Thanks in advance.

**Comment by haxelion** [comment]
It will only pick the object if there is a detected shape in front of the camera. Do you see the same green polygon around your object than in the video ?

**Comment by ghost** [comment]
I see the object in blue polygon.

**Comment by haxelion** [comment]
Right it's the blue one.
I unfortunately don't have access to a Baxter robot anymore, thus all I can do is guide you through the code to help you debug your problem

The detection of the wheel beeing pressed is done [there](https://github.com/haxelion/baxter_pickandlearn/blob/master/src/pickandlearn.cpp#L52). Which should request a shape to the vision algorithm and transition to the next state of the state machine. Then, [when the result is available](https://github.com/haxelion/baxter_pickandlearn/blob/master/src/pickandlearn.cpp#L58), something should happen. Either [there is no shape](https://github.com/haxelion/baxter_pickandlearn/blob/master/src/pickandlearn.cpp#L61) and you should see `no result` in the console or you should see `Piece X saved` and the [robot should grip the piece](https://github.com/haxelion/baxter_pickandlearn/blob/master/src/pickandlearn.cpp#L75).

You should determine which code path is taken and what line doesn't work.

**Comment by ghost** [comment]
I could only see baxter detecting polygon in blue color, after that it doesn't pick the object when I press the wheel. It neither says "no result" nor "piece x saved". I don't know why this is happening.

**Comment by haxelion** [comment]
Without being able to reproduce (because I don't  have access to a Baxter robot) or without a root cause I can't fix it, sorry :/

**Comment by haxelion** [comment]
I was messaged by somebody else and was able to track the issue.

The Baxter ROS API changed with the Baxter SDK 1.2 and the message used to receive the wheel button state changed.

The button state was in this message: (https://github.com/RethinkRobotics/baxter_common/blob/release-1.1.1/baxter_core_msgs/msg/ITBState.msg)
But is now in this message: https://github.com/RethinkRobotics/baxter_common/blob/release-1.2.0/baxter_core_msgs/msg/NavigatorState.msg

I'm going to try remote fix it.

**Comment by haxelion** [comment]
The commit 24c49cdfcc7889c10b1ce0e275f09645f59aa449 in the branch fix_for_sdk_1.2 has been confirmed to solve this issue by a user.

**Comment by rojas70** [comment]
Thanks
